export default easing;
declare namespace easing {
    function inBack(t: any, b: any, c: any, d: any, s: any): any;
    function inBounce(t: any, b: any, c: any, d: any): any;
    function inCirc(t: any, b: any, c: any, d: any): any;
    function inCubic(t: any, b: any, c: any, d: any): any;
    function inElastic(t: any, b: any, c: any, d: any): any;
    function inExpo(t: any, b: any, c: any, d: any): any;
    function inOutBack(t: any, b: any, c: any, d: any, s: any): any;
    function inOutBounce(t: any, b: any, c: any, d: any): any;
    function inOutCirc(t: any, b: any, c: any, d: any): any;
    function inOutCubic(t: any, b: any, c: any, d: any): any;
    function inOutElastic(t: any, b: any, c: any, d: any): any;
    function inOutExpo(t: any, b: any, c: any, d: any): any;
    function inOutQuad(t: any, b: any, c: any, d: any): any;
    function inOutQuart(t: any, b: any, c: any, d: any): any;
    function inOutQuint(t: any, b: any, c: any, d: any): any;
    function inOutSine(t: any, b: any, c: any, d: any): any;
    function inQuad(t: any, b: any, c: any, d: any): any;
    function inQuart(t: any, b: any, c: any, d: any): any;
    function inQuint(t: any, b: any, c: any, d: any): any;
    function inSine(t: any, b: any, c: any, d: any): any;
    function linear(t: any, b: any, c: any, d: any): any;
    function outBack(t: any, b: any, c: any, d: any, s: any): any;
    function outBounce(t: any, b: any, c: any, d: any): any;
    function outCirc(t: any, b: any, c: any, d: any): any;
    function outCubic(t: any, b: any, c: any, d: any): any;
    function outElastic(t: any, b: any, c: any, d: any): any;
    function outExpo(t: any, b: any, c: any, d: any): any;
    function outQuad(t: any, b: any, c: any, d: any): any;
    function outQuart(t: any, b: any, c: any, d: any): any;
    function outQuint(t: any, b: any, c: any, d: any): any;
    function outSine(t: any, b: any, c: any, d: any): any;
}
